### ISSUE TITLE
Failed delayed_jobs should probably give up after a while

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/QuickSubmit#39]
Currently, the server we test against is throwing a 500 of some sort when we submit. This properly flags the submission as failed, but the job is retried indefinitely.

We probably want to just try once and then dequeue it with a mechanism to requeue manually for admins and/or programmatically on a timer for all failed jobs (i.e. cron to enqueue sword submission of all Submissions with a failed status nightly maybe?).

If we want to rely on admins handling this, we should probably send an email on failure (or nightly summary of failures or whatever).

**Comment by richardrodgers** [comment]
Is there any config data QS has about the target server beyond the SWORD deposit endpoint?

**Comment by richardrodgers** [comment]
(and credentials, of course)

**Comment by JPrevost** [comment]
Nope. At this point it just blindly throws a sword package at a Sword server and assumes it'll all work out fine. (Well, it does handle errors back but not in a very sophisticated way).

Were you thinking of something specific?

**Comment by richardrodgers** [comment]
Not really - I was just wondering if there was an admin email or something, for just these sorts of situations (the admin email wouldn't have to even be DSpace-related, but could be)

**Comment by JPrevost** [comment]
We do have Users with admin roles in QuickSubmit itself that can be bugged about these types of errors for now at least.

**Comment by richardrodgers** [comment]
Yea, why not low-bar it for now?
