### ISSUE TITLE
Update METS and confirm Crosswalks

### ISSUE THREAD

**Issue by JPrevost** [MITLibraries/QuickSubmit#48]
Determine appropriate field and add:
- [x]  Expected Publication Date. Decision: `dc.date.issued`
- [x] one or more Funders Decision: `dc.description.sponsorship (repeatable)`

**Comment by cjrobles** [comment]
Publication date: dc.date.issued
Funders: dc.description.sponsorship (this is a repeatable field so each funding organization would have its own dc.description.sponsorship field.  No mechanism to store in metadata the funding award identifier and associate it with the proper funding organization.  Therefore, both elements are stored together in one field, with the award ID in parentheses).

Here’s an example page with multiple funders and award ID in parentheses:
https://dspace.mit.edu/handle/1721.1/101232?show=full

**Comment by JPrevost** [comment]
Thanks @cjrobles !

Just a note: it was decided in the demo meeting to not ask for grant numbers which removes the necessity to add them in parens. In other words we'll still have the repeatable fields, but just insert the straight text into each one that Ellen has provided for the funders and not have to combine with an associated grant number  (yay).
